### ISSUE TITLE
NULLs in writer

### ISSUE THREAD

**Issue by babourine** [scritchley/orc#10]
Sorry if this is something obvious. Trying to write nils to float64, int64 and strings. Getting a number of errors (Expected float64 got <nil> and similar) Was wondering if that is supported and if so what's the right way to have null in a column? Otherwise non-null values are written just fine. Thanks a lot for an awesome work!

**Comment by scritchley** [comment]
Hmm, yes, that should be supported, I'll look into this.

**Comment by scritchley** [comment]
There was an issue with the float and string writers, they were not handling nil values correctly. Integers should have been OK though. PR is here: https://github.com/scritchley/orc/pull/12

**Comment by scritchley** [comment]
PR is merged, can you confirm whether this fixes the issue for you.

**Comment by scritchley** [comment]
Closing this issue, feel free to reopen if the problem persists.
