### ISSUE TITLE
Issues reading Orc's from Spark output

### ISSUE THREAD

**Issue by tristanwietsma** [scritchley/orc#15]
Noticed two issues reading Orc generated by Spark.

- Reading a file `getmerged` out of HDFS results in `proto: proto.StripeFooter: wiretype end group for non-group`. The schema can be read fine, but can't access the stream.
- Reading a file generated via Spark on local, iteration through the stripes isn't working (infinite loop) and  the types are coming up as zeros.

For the former, can't replicate on local and the data is work related, but the latter you can replicate pretty easily:

![screen shot 2017-06-15 at 10 52 23 am](https://user-images.githubusercontent.com/1371478/27190152-2d9718de-51b9-11e7-942e-0e103e138b42.png)

**Comment by scritchley** [comment]
I'll have a look into this. Would you be able to upload the file you created locally for the second issue?

Regarding the first issue, if you are using `getmerge`, does that mean you are concatenating multiple ORC files? That would not be supported by this reader as it stands. Can you confirm whether it is supported by other reader implementations? As far as I know, two ORC files concatenated together would not result in a valid ORC file.

**Comment by tristanwietsma** [comment]
Yep, will do.

You're most likely right regarding the getmerge; I'll coalesce to 1 and try again.

**Comment by tristanwietsma** [comment]
[Orc sample, Snappy default compression](https://github.com/scritchley/orc/files/1167543/orc.zip)
[Orc sample, no compression](https://github.com/scritchley/orc/files/1167544/orc-nocomp.zip)

![screen shot 2017-07-22 at 1 29 47 pm](https://user-images.githubusercontent.com/1371478/28493775-e50d6546-6ee1-11e7-8021-95d68e25f7b0.png)

**Comment by scritchley** [comment]
Just following up on this, I have no issues reading both of the files you've posted. If you are still seeing the issue, can you provide the error output? We did merge some fixes to the reader implementation a while back, so the errors you saw might have been resolved.

**Comment by scritchley** [comment]
Closing this for now. If the issue persists, please feel free to reopen.
