### ISSUE TITLE
fix cursor.go

### ISSUE THREAD

**Issue by fs-sasaki-seido** [scritchley/orc#21]
Hi, we are using the library to read and write orc files. 

We've noticed an issue about "orc/cursor.go:85" 's comparison processing between currentRow and stripeRow Count. 
Seems like there is no chance for currentRow's data to be reset, so if the file has more than 2 stripe, all the objects comming after the first one won't be read out. We've already done with the program modification which the data will return to be 0 in Stripes(), so if you don't mind, could you please merge it?

Thank you.

**Comment by scritchley** [comment]
Thanks for the contribution, this has been merged.
