### ISSUE TITLE
More writer types

### ISSUE THREAD

**Issue by binary132** [scritchley/orc#23]
- [ ] `orc.Date`
- [ ] `orc.Decimal`
- [ ] (others?)

(Are you planning to promote the Writer to a supported state?)

**Comment by scritchley** [comment]
Yep, I will be working on implementing the remaining writers over the coming weeks. Namely date, decimal and union.

**Comment by scritchley** [comment]
Closing this in favour of the new issues here: 
https://github.com/scritchley/orc/issues/27 
https://github.com/scritchley/orc/issues/26
https://github.com/scritchley/orc/issues/25

**Comment by binary132** [comment]
:clap: thanks!
