### ISSUE TITLE
subsequent calls to select do not reset row index (cursor)

### ISSUE THREAD

**Issue by 5k3105** [scritchley/orc#33]
Hi,

code is like:

```go
		files, err := orc.Open(orcfile)
		if err != nil {
			println(err.Error())
		}
```
and later:

```go
		c := files.Select("fid", "fname", "filesize")
```
First pass, it returns values.

When I don't open the file again and run ```c := files.Select("fid", "fname", "filesize")``` again later, it seems to return nothing.

It seems like the cursor runs to the end of the recordset and subsequent calls to renew the cursor do not reset it's position?

If I open the file again and run select, I get output.

my loop code like:

```go
for c.Stripes() {
   println("stripe ok")
      for c.Next() {
```

subsequent calls, it doesn't get to the print statement.

**Comment by scritchley** [comment]
Yep, this is known issue which I have fixed in a local development branch. I will aim to get it merged to master soon.

**Comment by 5k3105** [comment]
Thanks!

**Comment by scritchley** [comment]
This should be solved now, I will close preemptively, feel free to reopen if the behaviour is not as expected.
