### ISSUE TITLE
Set OrcProto.Footer.writer and PostScript.writerVersion

### ISSUE THREAD

**Issue by omalley** [scritchley/orc#34]
We've added a code for your writer implementation. You should set:

    Footer.writer = 3
    PostScript.writerVersion = 6 (or higher)

to ensure that the different ORC readers can distinguish between the various writers when they need to work around bugs in the writers.

Your implementation's writer id was added here - https://issues.apache.org/jira/browse/ORC-249

**Comment by scritchley** [comment]
Thanks! I'll get this added.

**Comment by scritchley** [comment]
Merged: https://github.com/scritchley/orc/pull/35
