### ISSUE TITLE
Reading Decimals

### ISSUE THREAD

**Issue by cognusion** [scritchley/orc#37]
I'm working on reading the OSM Planet data, which has a pair of columns for latitude and longitude, defined as : lat:decimal(9,7),lon:decimal(10,7)

On Open, typdescription's withPrecision fires off an error: "precision 9 is out of range of 1 .. 10". Reading the case for this:

`if precision < 1 || precision > maxPrecision || t.scale > precision`

I assume that t.scale (which defaults to 10)  being larger than the lat precision is where the problem lies. Naively flipping that operator around does allow the file to be read, and I can read other columns fine, but both lat and lon are always `{<nil> 0}`, so I assume there's another problem elsewhere.

Thoughts?

The 50GB file in question is publicly available at s3://osm-pds/planet/planet-latest.orc if that helps. I'm also happy to provide more information as needed. Thanks

**Comment by scritchley** [comment]
I think I know what the issue is. Will hopefully have a fix ready shortly.

**Comment by scritchley** [comment]
This should now be fixed. I've tested with s3://osm-pds/planet/planet-latest.orc and it looks like all the decimal values are being returned correctly now.

**Comment by cognusion** [comment]
@scritchley Confirmed, running as-expected now: Thanks!

**Comment by reinholdk** [comment]
Looks like DECIMAL(10,0) is not supported correctly yet, even after this fix. It is read as DECIMAL(10,10) whereas the native orc-metadata tool reads DECIMAL(10,0)

What do you think?
