### ISSUE TITLE
add read orc file on hdfs

### ISSUE THREAD

**Issue by dalizitajiu** [scritchley/orc#46]
I have seen how to read parquet file on hdfs, but I dont known how to read or write orc file on hdfs ,count you add example?

**Comment by scritchley** [comment]
Thanks for the issue but this isn't in the scope of this project. This package focuses on reading/writing ORC files and doesn't deal directly with HDFS. Theoretically, you would just need to implement the orc.SizedReaderAt and an io.Writer interface and this package would support it though, which should be fairly straightforward.
