### ISSUE TITLE
TimeStamp statistic not available?

### ISSUE THREAD

**Issue by Jeremyyang920** [scritchley/orc#53]
Im trying to currently extract the timestamp static out of the fields, but it always seems like its nil.

I modified one of the writer test to just write a timestamp and read the file in, but theres no timestamp statistic. 

```go
c := r.Select("int1", "timestamp1")
	for c.Stripes() {
		for c.Next() {
			fmt.Println(r.getTypes())
			fmt.Println(c.Row())
		}
	}
        //custom defined method to get statistic for a certain field
	fmt.Println(r.ColumnStatistics("timestamp1"))
```

I see the type is recorded correctly, but theres no statistic.
numberOfValues:5 hasNull:false  <nil>

The full output of statistics is 
[numberOfValues:5 hasNull:false  numberOfValues:5 hasNull:false  numberOfValues:5 intStatistics:<minimum:51 maximum:9410 sum:22770 > hasNull:false ]

**Comment by Jeremyyang920** [comment]
Nevermind. I figured out that it was just not set up at all and that all timestamps end up being written as a BaseStatistic

**Comment by scritchley** [comment]
Thanks for contributing! Apologies I took so long to get round to the review.
