### ISSUE TITLE
Boolean data is written wrong after 10000 rows

### ISSUE THREAD

**Issue by Jeremyyang920** [scritchley/orc#61]
Something that I discovered which debugging something was that boolean data gets written out incorrectly after 10000 rows have been written out.  It could happen less since I have seen it in our services that are capped at 5000 rows, but I could consistently replicate the issue using the TestWriter test with 1000 rows. 

I set up the test to write the following  schema 
`struct<int1:int,boolean1:bool>`

I wrote a combination of true, false, and nils out for the boolean values then read the file in row by row and did an assertion that it was the right row. 

After 10000 rows, the test would break because of an assertion failure in which the boolean value for boolean1 was incorrect. Trues would be falses and falses would be true. I was able to mitigate this by changing the DefaultStripeTargetRowCount to 10000 and was then able to do a test with 100000 rows and have it pass.

I can't seem to find where in the boolean writer, or the tree writers this issue is occurring.

**Comment by scritchley** [comment]
I've not been able to replicate this in a test. Are you able to post the test code that you found to cause the issue?

**Comment by Jeremyyang920** [comment]
`func TestWriter(t *testing.T) {
	f, err := ioutil.TempFile("", "testorc")
	if err != nil {
		t.Fatal(err)
	}

	filename := f.Name()
	defer os.Remove(filename) // clean up
	defer f.Close()

	schema, err := ParseSchema("struct<int1:int,boolean1:boolean>")
	if err != nil {
		t.Fatal(err)
	}

	w, err := NewWriter(f, SetSchema(schema))
	if err != nil {
		t.Fatal(err)
	}

	length := 10000
	for i := 0; i < length; i++ {
		if i%2 == 0 {
			err = w.Write(i, true)

		} else if i%3 == 0 {
			err = w.Write(i, nil)
		} else {
			err = w.Write(i, false)

		}
		if err != nil {
			t.Fatal(err)
		}
	}

	err = w.Close()
	if err != nil {
		t.Fatal(err)
	}

	// Read the writer output
	r, err := Open(filename)
	if err != nil {
		t.Fatal(err)
	}

	c := r.Select("int1", "boolean1")
	row := 0
	for c.Stripes() {
		for c.Next() {
			var expected []interface{}
			if row%2 == 0 {
				expected = []interface{}{int64(row), true}
			} else if row%3 == 0 {
				expected = []interface{}{int64(row), nil}
			} else {
				expected = []interface{}{int64(row), false}

			}
			assert.Equal(t, expected, c.Row())
			row++
		}
	}
}`

Above is the test that I was using. The assert library that we use is 	"github.com/stretchr/testify/assert" so that is also the one that i have in the test. When I adjust the length variable to be greater than 10000, the test will fail ( for me at least).  

Error Trace:	writer_test.go:91
        	Error:      	Not equal: 
        	            	expected: []interface {}{10999, false}
        	            	actual  : []interface {}{10999, true}
        	            	
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -2,3 +2,3 @@
        	            	  (int64) 10999,
        	            	- (bool) false
        	            	+ (bool) true
        	            	 }
        	Test:       	TestWriter


The above is usually the error where the type assertion is wrong.  Any length under 10000 always passes for me, but once i do like 10005, the test will fail.

Maybe I approached this the wrong way, but when I opened the issue, we were trying to debug an issue in one of our production services since we were seeing the data that came in, was not matching the data that got written out to orc and ingested into our data store.

**Comment by scritchley** [comment]
Ok, I think this change addresses the issue: https://github.com/scritchley/orc/pull/62

It seems to stem from flushing the writers at each row index interval (defaults to 10k). In hindsight, I think this is actually incorrect as the writers shouldn't be flushed we should just record and reset the row indexes. 

I've added a test to cover this case and all tests are passing locally, I just want to double check some things before merging.

**Comment by scritchley** [comment]
Thanks for your help with this!
