### ISSUE TITLE
Is README accurate?

### ISSUE THREAD

**Issue by mauidude** [scritchley/orc#9]
It appears you have no writer support listed in the README but I see a writer implementation and it looks to have been committed after the update to the README. What is the current status of write capabilities?

**Comment by scritchley** [comment]
Yes, there is a writer implementation that works, although, there are still cases where it's behaviour might not or does not conform to the ORC spec. Namely:
- Row indexes - It's quite hard to decipher exactly what the spec intends: https://orc.apache.org/docs/spec-index.html
- Compression - Currently all of the compression writers do not compress, they simple write the file uncompressed.

It's this that's made me refrain from declaring it as a supported feature. I'm waiting on a project that requires the writer functionality to more thoroughly test it.

**Comment by 5k3105** [comment]
Hi,
> I'm waiting on a project that requires the writer functionality to more thoroughly test it.

I have half a dozen projects that may benefit from a good compressed database format.

Looked at lmdb and sqlite. Haven't ever used orc though. I'm still unsure about how querying is done.

**Comment by binary132** [comment]
Hello @scritchley, we're looking at using your writer.  Do you think is working reasonably well?  I see you have zlib compression now.

How bad is the row index issue?

**Comment by scritchley** [comment]
The issue (if there is one) specifically relates to the 'positions' field in the row index detailed here: https://orc.apache.org/docs/spec-index.html

The writer as it stands does write the indexes, however, the code that writes the positions may not behave as intended by the spec. I suppose this could cause issues in readers that utilise the indexes to prune rows. I've had limited experience of this in practice though.

I would need to compare the row indexes created by this writer with those created by one of the official tools.

**Comment by scritchley** [comment]
Closing this for now. I will be making writer support official in the upcoming couple of weeks.

**Comment by binary132** [comment]
Hi @scritchley -- set my expectations? :)
